### ISSUE TITLE
Setting cron time fails

### ISSUE THREAD

**Issue by petermunch81** [oh2th/fi.oh2th.alarmutils#16]
**Describe the bug**
When trying to set a cron time, the card fails with the following error:
Cannot read properties of undefined (reading 'test')

**To Reproduce**
1. Add cron time card to adv. flow
2. Set cron time, eg: 0 13 * * *
3. Right click card and select test from here

**Expected behavior**
No errors and cron time set to schedule

**Screenshots**
![fejl](https://github.com/user-attachments/assets/9bc3cdaa-88a7-4c76-a354-4e348d14b7a4)

**App (please complete the following information):**
 - Live version
 - Installed version of Action Scheduler: v2.4.2
 - Model: Homey Pro (Early 2023)
- Version: 12.0.1

**Additional context**
HomeyId of report: f78134f6-a1fe-480d-aa65-950b2468b1c9

**Comment by oh2th** [comment]
Thank you for your very clear problem description. Found the issue and a fix is on its way.

**Comment by oh2th** [comment]
Fix is live at Homey App Store.

**Comment by petermunch81** [comment]
I can confirm that the fix is working as inteded 👍
Thanks for a quick response.
