### ISSUE TITLE
Status indicator in Homey device

### ISSUE THREAD

**Issue by Rrrr4321** [oh2th/fi.oh2th.alarmutils#3]
In the Homey mobile app, I would like to edit device settings and then set the Status indicator to the Time text field in the schedule.

**Comment by oh2th** [comment]
Thank you for the suggestion for a feature. I will look in to this one. It could be useful indeed. For now, the is a text variable for each device that can be used. It either has the next run time, or "Not scheduled"

**Comment by oh2th** [comment]
Sorry to disappoint you, but seems that text (string) values can not be used in status indicators:

https://apps.developer.homey.app/the-basics/devices/capabilities#device-indicators-and-custom-capabilities

However, I have added next scheduled date and time to the sensors view.

**Comment by Rrrr4321** [comment]
Found them, that is a nice solution, thank you. I added an example to the community thread.
