### ISSUE TITLE
Renamed alarm not visible

### ISSUE THREAD

**Issue by Rrrr4321** [oh2th/fi.oh2th.alarmutils#4]
1.
I created a new device with an alarm and named it Hot water 1 Morning.
After a while I renamed it to 0532 Hot water, but the new name is not visible in Select alarm

![image](https://user-images.githubusercontent.com/47206391/224053176-32cdd81c-4e34-440b-87ef-378ab36d0711.png)

2. I created more devices with each a different alarm time.
The new alarms are not visible in Select alarm either. I tried to refresh

**Comment by oh2th** [comment]
You would need to swap the Then card to the one under each device:
<img width="740" alt="Screenshot 2023-03-12 at 6 03 03" src="https://user-images.githubusercontent.com/59442255/224523641-e39ec6b7-6678-4536-aa98-4ca1aa4cf679.png">

The card you now have is the one for Homey Alarms. Each device has their own flow cards.
