### ISSUE TITLE
Implement When an alarm goes off in x minutes

### ISSUE THREAD

**Issue by Rrrr4321** [oh2th/fi.oh2th.alarmutils#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rrrr4321** [comment]
Reference[Reference](https://community.homey.app/t/app-pro-action-scheduler-alarm-utilities/75592/33?u=rrrr)

**Comment by oh2th** [comment]
Thank you for your suggestion. 
This might be slightly more complex for the app due to how it utilizes a cron-library internally. I will look in to this if it is possible without increasing the memory usage for the app.

**Comment by oh2th** [comment]
Note to self, possible an interval that checks the running schedules and triggers When cards with a tag with the triggering Scheduler. Should be one interval to rule them all, so that memory usage is reasonable.
