### ISSUE TITLE
Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.

### ISSUE THREAD

**Issue by oh2th** [oh2th/fi.oh2th.alarmutils#8]
https://github.com/kelektiv/node-cron/issues/467

Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.
							Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
							Time Zone: "" - Cron String: 0 * * * * * - UTC offset: 0
							- current Date: 2023-03-21T21:02:30.288+00:00
    at CT._getNextDateFrom (/app/node_modules/cron/lib/time.js:272:12)
    at CT.sendAt (/app/node_modules/cron/lib/time.js:185:17)
    at CT.getTimeout (/app/node_modules/cron/lib/time.js:202:29)
    at CJ.start (/app/node_modules/cron/lib/job.js:118:31)
    at Timeout.callbackWrapper [as _onTimeout] (/app/node_modules/cron/lib/job.js:171:11)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by oh2th** [comment]
Updated cron node-module to version 2.3.0 as referenced in https://github.com/kelektiv/node-cron/issues/467

**Comment by intcreator** [comment]
hey I help maintain node-cron. I'm trying to figure out if this issue is due to high CPU usage or something similar so let me know if you have more details on that

**Comment by oh2th** [comment]
> hey I help maintain node-cron. I'm trying to figure out if this issue is due to high CPU usage or something similar so let me know if you have more details on that

Thanks for your input on this. I'm monitoring this now after updating to 2.3.0 of node-cron.

The code runs on a Athom Homey Pro 2023 early access home automation device and there also still issues also on the hardware itself. 

One thing that has been resently noticed that the power supply delivered with it, may drop voltage impacting theb for the cpu clock to drop.

Need to test with a better power source also.

**Comment by oh2th** [comment]
@intcreator, for now for the reports I get from users, it seems that the problem is not related to high CPU. But I will keep monitoring how it goes.

**Comment by intcreator** [comment]
thanks for your help in debugging this. how about RAM usage? based on recent comments on the canonical issue you linked above insufficient RAM might cause this to occur

if we do get out of sync maybe we can simply emit a warning that it happened rather than causing a hard failure and attempt to continue the cron job. I think that was talked about before I started helping maintain the repo so I'll have to look into it more. it's possible that could cause silent erroneous behavior if cron remains out of sync after emitting the warning

**Comment by oh2th** [comment]
node-cron 2.1.4 may now fix the issue. So bumping the package requirement to that.

**Comment by oh2th** [comment]
Should fix FI-OH2TH-ALARMUTILS-1
